### ISSUE TITLE
Links on Kubernetes installation landing page.

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/kubernetes-docs#104]
Searching for "ubuntu kubernetes install" gives me this page as the second hit: https://www.ubuntu.com/kubernetes/install . There we point people to https://conjure-up.io/?_ga=2.116028230.1377729411.1551626915-812808229.1551626915 . Should we instead point to https://www.ubuntu.com/kubernetes/docs/quickstart ?

**Comment by evilnick** [comment]
I'll take a look, but that's a www.ubuntu.com issue, not a docs one. I re-opened it here:

https://github.com/canonical-websites/www.ubuntu.com/issues/4783
