### ISSUE TITLE
Release notes for 1.14 patch release

### ISSUE THREAD

**Issue by tvansteenburgh** [juju-solutions/kubernetes-docs#144]
- Fixed Ceph PV fails to mount in pod ([Issue](https://bugs.launchpad.net/cdk-addons/+bug/1820908)) 
 - Fixed Problems switching from kube-dns to CoreDNS ([Issue](https://bugs.launchpad.net/charm-kubernetes-master/+bug/1822001))
 - Fixed defaultbackend-s390x image ([Issue](https://github.com/juju-solutions/kubernetes/pull/229))
 - Fixed `keystone-ssl-ca` config description ([Issue](https://github.com/juju-solutions/kubernetes/pull/230))
 - Partial fix for using custom CA with Keystone ([Issue](https://github.com/juju-solutions/cdk-addons/pull/91))

**Comment by Cynerva** [comment]
LGTM

**Comment by tvansteenburgh** [comment]
This release will be in bundles:

charmed-kubernetes-3
canonical-kubernetes-471

**Comment by evilnick** [comment]
thanks! Is this going to be live imminently? the charm store still claims 466 is latest stable

**Comment by tvansteenburgh** [comment]
The release job is running now.
